spring.application.name=blog-platform
#1. PostgreSQL connection settings
spring.datasource.url=${DATABASE_URL}

spring.datasource.driver-class-name=org.postgresql.Driver

#2. JPA / Hibernate Automation settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
